# Generated by Django 3.0.7 on 2020-07-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('email', models.CharField(max_length=60, verbose_name='Email')),
                ('celular', models.CharField(max_length=13, verbose_name='Celular')),
                ('comentarios', models.CharField(max_length=200, verbose_name='Comentários')),
            ],
        ),
    ]
