# Generated by Django 3.0.7 on 2020-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='tipo',
            field=models.CharField(choices=[('Imóvel', 'Imóvel'), ('Contato', 'Contato')], max_length=7),
        ),
    ]
