# Generated by Django 3.0.7 on 2020-07-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200728_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='tipo',
        ),
    ]
