# Generated by Django 3.0.7 on 2020-07-07 19:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descrição'),
        ),
    ]
