# Generated by Django 3.0.7 on 2020-07-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_auto_20200708_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='imoveis',
            name='suites',
            field=models.IntegerField(default=0),
        ),
    ]
