# Generated by Django 3.0.7 on 2020-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_imoveis_suites'),
    ]

    operations = [
        migrations.AddField(
            model_name='imoveis',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imoveis',
            name='rua',
            field=models.CharField(default='', max_length=100, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='tipo',
            field=models.CharField(choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa'), ('Sobrado', 'Sobrado'), ('Kitnet', 'Kitnet'), ('Loft', 'Loft'), ('Terreno', 'Terreno')], default='', max_length=100, verbose_name='Tipo'),
        ),
    ]
