# Generated by Django 3.0.7 on 2020-07-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_auto_20200720_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='rua',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Rua'),
        ),
    ]
