# Generated by Django 3.0.7 on 2020-07-27 18:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_auto_20200720_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='imoveis',
            name='rua',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Rua'),
        ),
    ]
