# Generated by Django 3.0.7 on 2020-08-05 18:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_auto_20200727_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500, verbose_name='Descrição'),
        ),
    ]
